baseURL = "https://www.marcelkraus.de/"
theme = "devresume"

languageCode = "de"
defaultContentLanguage = "de"
title = "Marcel Kraus, Softwareentwickler (iOS & Web)"

[params]
    author = "Marcel Kraus"
    description = "Marcel Kraus aus Erftstadt bei Köln, Softwareentwickler (iOS & Web) bei der Chefkoch GmbH in Bonn und selbstständiger IT-Dienstleister."
    primaryColor = "#FD9E1C"
    textPrimaryColor = "#1B1B1B"
    [params.profile]
        enable = true
        name = "Marcel Kraus"
        tagline = "Ein Softwareentwickler mit vielen Qualitäten"
        avatar = "avatar.jpg"
    [params.contact]
        enable = true
        location = "Erftstadt (bei Köln)"
        [[params.contact.list]]
            icon = "fas fa-envelope-square"
            text = "hallo (at) marcelkraus.de"
    [params.summary]
        enable = true
        text = "Hallo, ich bin Marcel!\n\nIch bin Softwareentwickler mit Produkt-Erfahrung: Bei der Chefkoch GmbH in Bonn entwickle ich native Apps für iOS (iPhone & iPad), ausserdem schreibe ich Microservices für das Web (unter Verwendung von Symfony).\n\nDarüber hinaus bin ich nebenberuflich selbstständig tätig: Solltest du also einen Softwareentwickler, Produktmanager oder generell einen IT-Dienstleister suchen, sprich mich gerne an.\n\nIch habe Benzin (bzw. Strom) im Blut: In meiner Freizeit blogge ich über die Erfahrungen mit meinem Tesla Model 3, die Restauration meines Pontiac Trans Am, fahre über die legendäre Nordschleife oder sitze in meinem Rennsimulator."
    [params.experience]   
        enable = true
        [[params.experience.list]]
            title = "iOS-Entwickler"
            dates = "Seit 07/2017"
            company = "Chefkoch GmbH, Bonn"
            details = "Fortlaufende Entwicklung und Integration der iOS-, watchOS- und 	tvOS-Apps des Unternehmens unter Verwendung von Objective-C und Swift; seit Juli 2019: Neuentwicklung der bestehenden Chefkoch-App unter Verwendung der “hybriden“ Technologie-Plattform Flutter für Android und iOS."
        [[params.experience.list]]
            title = "IT-Dienstleister"
            dates = "Seit 10/2002"
            company = "Einzelunternehmer, Erftstadt"
            details = "Konzeption und Entwicklung von Webanwendungen und Apps für Apple iOS; Administration von Linux-Server-Umgebungen; Consulting und Support	für Hard- und Software-Produkte der Firma Apple, Inc."
        [[params.experience.list]]
            title = "PHP-Entwickler"
            dates = "07/2016 bis 06/2017"
            company = "Chefkoch GmbH, Bonn"
            details = "Fortlaufende Entwicklung und Integration des Content-Management-Systems Drupal 8 in die bestehende Umgebung."
        [[params.experience.list]]
            title = "Projektleiter"
            dates = "01/2011 bis 06/2016"
            company = "ASB Deutschland e.V., Köln"
            details = "Leitendes Projektmanagement bei Neu- und Weiterentwicklungen der Webanwendungen; Konzeption und Entwicklung von Webanwendungen; Anforderungsanalyse im Rahmen der Erneuerung der vorhandenen Businessanwendungen."
        [[params.experience.list]]
            title = "Web-Entwickler"
            dates = "10/2004 bis 12/2010"
            company = "ASB Deutschland e.V., Köln"
            details = "Konzeption und Entwicklung von Webanwendungen; Technische Betreuung der Content-Management-Systeme; Administration des Dokumenten-Management-Systems Regisafe; Endbenutzer-Support."

        [params.projects]
            enable = true
            [[params.projects.list]]
                title = "T wie TESLA"
                meta = "Persönlicher Blog"
                tagline = "Ich habe den Einstieg in die E-Mobiltät gewagt und fahre seit dem 19. Juni 2019 ein Model 3 von Tesla. Auf “T wie TESLA” schreibe ich über meine Erfahrungen mit dem Model 3, dem Tesla-Ökosystem und meinen generellen Erfahrungen."
                [[params.projects.list.link]]
                    url = "https://www.twietesla.de"
                    title = "Besuche meinen Blog “T wie TESLA“…"
                    localizedUrl = "https://www.twietesla.de"
            [[params.projects.list]]
                title = "myKNIGHT.de"
                meta = "Persönlicher Blog"
                tagline = "Aktuell restauriere ich einen 1982er Pontiac Firebird Trans Am, dir ganz sicher bekannt als “K.I.T.T.” aus “Knight Rider”. Auch wenn die Restauration etwas länger dauert, irgendwann spürt mein Trans Am wieder die Straße unter seinen Reifen."
                [[params.projects.list.link]]
                    url = "https://www.myknight.de"
                    title = "Besuche meinen Blog “myKNIGHT.de”…"
                    localizedUrl = "https://www.myknight.de"
            [[params.projects.list]]
                title = "Tacho – Wie schnell bin ich?"
                meta = "iOS-App"
                tagline = "“Tacho – Wie schnell bin ich?” ist eine werbefreie und kostenlose Tacho-App für deine Hosentasche. Ohne störende Werbebanner zeigt dir “Tacho” die deine aktuelle Geschwindigkeit und deine aktuellen Position."
                [[params.projects.list.link]]
                    url = "https://tacho.marcelkraus.de"
                    title = "Besuche die Landingpage für meine iOS-App “Tacho – Wie schnell bin ich?”…"
                    localizedUrl = "https://tacho.marcelkraus.de"
    [params.information]
        enable = true
        [[params.information.list]]
            title = "Impressum"
            [[params.information.list.items]]
                details = "Adresse: Marcel Kraus, Dreikönigenweg 8a, 50374 Erftstadt  \nMail: hallo (at) marcelkraus.de  \nFon: +49 2235 8401372"
        [[params.information.list]]
            title = "Datenschutz"
            [[params.information.list.items]]
                details = "Der Schutz deiner Daten hat für mich einen hohen Stellenwert. Diese Seite ist frei von Tracking-Codes und Cookies, Log-Dateien des Webservers werden nicht ausgewertet. Dennoch freue ich mich über eine persönliche E-Mail von dir… :)"
    [params.education]
        enable = false
    [params.awards]
        enable = false
    [params.skills]
        enable = true
        [[params.skills.list]]
            title = "Programmiersprachen"
            [[params.skills.list.items]]
                details = "- Dart"
            [[params.skills.list.items]]
                details = "- Objective-C"
            [[params.skills.list.items]]
                details = "- PHP"
            [[params.skills.list.items]]
                details = "- Swift"
            [[params.skills.list]]
                title = "Frameworks"
                [[params.skills.list.items]]
                    details = "- Cocoa Touch"
                [[params.skills.list.items]]
                    details = "- Flutter"
                [[params.skills.list.items]]
                    details = "- Symfony"
        [[params.skills.list]]
            title = "Projektmanagement"
            [[params.skills.list.items]]
                details = "- Kanban"
            [[params.skills.list.items]]
                details = "- PRINCE 2"
            [[params.skills.list.items]]
                details = "- Scrum"
    [params.languages]
        enable = true
        [[params.languages.list]]
            name = "Deutsch"
            level = "Muttersprache"
        [[params.languages.list]]
            name = "Englisch"
            level = "Fließend"
        [[params.languages.list]]
            name = "Kölsch"
            level = "För et Hätz"
    [params.interests]
        enable = true
        [[params.interests.list]]
            name = "Automobiles Kulturgut"
        [[params.interests.list]]
            name = "Klemmbausteine"
        [[params.interests.list]]
            name = "Motorsport"
        [[params.interests.list]]
            name = "Sim Racing"
    [params.social]
        enable = true
        [[params.social.list]]
            icon = "fab fa-github-square"
            url = "//github.com/marcelkraus"
            title = "marcelkraus"
        [[params.social.list]]
            icon = "fab fa-twitter-square"
            url = "//twitter.com/marcelkraus"
            title = "@marcelkraus"
        [[params.social.list]]
            icon = "fab fa-xing-square"
            url = "//www.xing.com/profile/Marcel_Kraus2"
            title = "@Marcel_Kraus2"
