baseurl = "https://www.marcelkraus.de"
defaultContentLanguage = "de"
languageCode = "de-DE"
title = "Marcel Kraus: iOS-Entwickler und IT-Dienstleister aus Erftstadt"
theme = "sam"
enableRobotsTXT = true
preserveTaxonomyNames = true
googleAnalytics = "UA-12561257-14"

[permalinks]
    blog = "/blog/:slug/"

[params]
    dateform = "02.01.2006"
    dateformfull = "02.01.2006"
    homepage = "Der Anfang"
    footerText = "<small>[Blog nach Tags](/tags/) • [Marcel auf Twitter](https://www.twitter.com/marcelkraus) • [Marcel auf GitHub](https://github.com/marcelkraus)<br/>[Impressum](/impressum/) • [Datenschutz](/datenschutz/)</small>"
    description = "Marcel Kraus ist ein iOS-Entwickler bei der Chefkoch GmbH und selbstständiger IT-Dienstleister aus Erftstadt bei Köln."
    twitterCard = "summary_large_image"
    primaryImage = "/images/avatar-small.jpg"

[[params.mainMenu]]
    link = "/ueber-marcel/"
    text = "Über Marcel"

[[params.mainMenu]]
    link = "/blog/"
    text = "Marcel bloggt"
