title = "Marcel Kraus"
baseURL = "https://blog.marcelkraus.de"
theme = "bilberry-hugo-theme"
defaultContentLanguage = "de"
languageCode = "de-DE"
enableRobotsTXT = true
preserveTaxonomyNames = true
googleAnalytics = "UA-12561257-14"

[params]
  author = "Marcel Kraus"
  subtitle = "Ein Leben zwischen iOS und Werkstatt"
  description = "Getreu meinem Motto &quot;Stay hungry, stay foolish&quot; sind Apple-Produkte und das Internet seit über 15 Jahren gleichermaßen meine Berufung und Leidenschaft."
  customImage = "/images/avatar-small.jpg"
  permanentTopNav = true
  paginate = 10
  facebook = "https://www.facebook.com/kraus.marcel"
  github = "https://github.com/marcelkraus"
  twitter = "https://twitter.com/marcelkraus"
  youtube = "https://www.youtube.com/channel/UCg2p961BjzCqTKH4pPAAiYg"

[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"
